config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#hi'
  resources :users do
    member do
      post "hascomment"
      post "hasnotcomment"
    end
  end
  resources :departments do
    member do
      post "like2" =>  "departments#like2"
      post "unlike2" => "departments#unlike2"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :owner, polymorphic: true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :tenants
    has_many :users ,:through => :tenants
    has_many :likes, as: :owner, dependent: :destroy
    has_many :comments,  as: :owner, dependent: :destroy
    def find_like(user)
      self.like2s.where( :user_id => user.id ).first
    end
end

app/models/like2.rb
class Like2 < ApplicationRecord
    belongs_to :user, class_name: 'User'
    belongs_to :owner, polymorphic: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
    belongs_to :user
    belongs_to :department,optional: true
    #belongs_to :yy
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tenants
    has_many :departments, :through => :tenants 
    has_many :comments,  as: :owner, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

def index
  @departments = Department.all
end

def new
  @department = Department.new
end

def create
  @department = Department.new(de_params)

  @department.save

  redirect_to departments_url
end

def edit
end 

def update
end 

def destroy
end 

def show 
end
def like2
     @department = Department.find(params[:id])
     unless @department.find_like(current_user)  # 如果已经按讚过了，就略过不再新增
        Like2.create( :user => current_user, :department => @department)
      end
  
      redirect_to users_path
    end
  
    def unlike2
      @department = Department.find(params[:id])
      like2 = @department.find_like(current_user)
      like.destroy
  
      redirect_to posts_path
    end

private

def de_params
  params.require(:department).permit(:name )
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  
    @user.save
  
    redirect_to users_url
  end

  def edit
  end 

  def update
  end 

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end 

  def show 
    @user = User.find(params[:id])
  end
  
  def hascomment
    @user = User.find(params[:id])
    Comment.create(:owner => @user)
    redirect_to user_path(@user)
  end

  def hasnotcomment
    @user = User.find(params[:id])
    comment = @user.comments.first
    comment.destroy
    redirect_to user_path(@user)
  end
  private

  def user_params
    params.require(:user).permit!
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hi
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/departments/index.html.erb
<ul>
  <% @departments.each do |user| %>
    <li>
      <%= user.name %>

      <%= link_to "Show", department_path(user) %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= button_to 'Delete', user_path(user), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
  <% end %>
</ul>
  
  <%= link_to 'New User', new_department_path %>

app/views/departments/new.html.erb
<%= form_for @department, :url => departments_path do |f| %>
    <%= f.label :login_name, "Name" %>
    11
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyToMany</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.login_name %>
      <%= user.departments.name %>
      <% user.departments.each do |g| %>
        <%= g.name %>
      <% end %>
      <% if !user.comments.present? %>
        <%= link_to "good", hascomment_user_path(user), :method => :post %>
      <% else %>
        <%= link_to "notgood", hasnotcomment_user_path(user), :method => :post %>
      <% end %>
      <%= link_to "Show", user_path(user) %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= button_to 'Delete', user_path(user), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
  <% end %>
</ul>
  
  <%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path do |f| %>
    <%= f.label :login_name, "Name" %>
    11
    <%= f.text_field :login_name %>
    <%= f.collection_check_boxes(:department_ids, Department.all, :id, :name) %>
    <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<a>hi</a>
<p>Group:
	<% @user.departments.each do |g| %>
		<%= g.name %>
	<% end %>
</p>

app/views/welcome/hi.html.erb
<a>hi!</a>